array(
  //'nid' => '10',
  'type' => 'page',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1319622700',
  'changed' => '1327476216',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  //'vid' => '73',
  'revision_uid' => '1',
  'title' => 'Add a New Tool',
  'body' => '<p>
	Here you can add your widget to the Widget Store. Please note the <a href="http://www.role-widgetstore.eu/faq" target="_blank">FAQs </a>
	before adding your tool. The Widget Store supports <a href="http://www.opensocial.org/" target="_blank">OpenSocial </a>  
	and W3C widget specifications.
</p>

<p>
	To submit a tool you must have been registered at the store. You can get an account <a href="/user/register" target="_blank">here</a>.
</p>

<p>
	You can also add tools where you are not the author if this is allowed by the given licence.
</p>

<p>
	After you submitted a tool a member of the ROLE consortium will review your tool and either publish it or contact you because of 
	possible improvement. You can see the status of the tool at the My Tools page.
</p>



<p>&nbsp;</p>

<p style="text-align: center;">
	<a class="form-submit" href="/node/add/lstool-opensocial">
		<img src="/sites/default/files/add_os.png" alt="Add New OpenSocial Tool" />
	</a>
	<a class="form-submit" href="/node/add/lstool-w3c">
		<img src="/sites/default/files/add_w3c.png" alt="Add New OpenSocial Tool" />
	</a>
</p>

',
  'teaser' => '<p>
	Here you can add your widget to the Widget Store. Please note the <a href="http://www.role-widgetstore.eu/faq" target="_blank">FAQs </a>
	before adding your tool. The Widget Store supports <a href="http://www.opensocial.org/" target="_blank">OpenSocial </a>  
	and W3C widget specifications.
</p>

<p>
	To submit a tool you must have been registered at the store. You can get an account <a href="/user/register" target="_blank">here</a>.
</p>

<p>
	You can also add tools where you are not the author if this is allowed by the given licence.
</p>',
  'log' => 'removed contest',
  'revision_timestamp' => '1327476216',
  'format' => '3',
  'name' => 'admin',
  'picture' => '',
  'data' => 'a:2:{s:29:"taxonomy_image_disable_images";i:0;s:13:"form_build_id";s:37:"form-07d8ef4935e022738422a075001088ec";}',
  'path' => 'add-new-tool',
  'last_comment_timestamp' => '1320680094',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'files' => array(),
  'menu' => array(
  ),
  '#_export_node_encode_object' => '1',
);