array(
  //'nid' => '19',
  'type' => 'page',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1330700882',
  'changed' => '1330700882',
  'comment' => '0',
  'promote' => '1',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  //'vid' => '19',
  'revision_uid' => '1',
  'title' => 'Please login or register',
  'body' => '<p style="text-align: left;">The page you requested is for restricted to registered users. Please login or register to proceed to the page.</p>',
  'teaser' => '<p style="text-align: left;">The page you requested is for restricted to registered users. Please login or register to proceed to the page.</p>',
  'log' => '',
  'revision_timestamp' => '1330700882',
  'format' => '3',
  'name' => 'admin',
  'picture' => '',
  'data' => 'a:0:{}',
  'path' => 'please-login-or-register',
  '_workflow' => FALSE,
  'last_comment_timestamp' => '1330700882',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'files' => array(),
  'imgupload_images' => array(),
  'menu' => array(
    'link_title' => '',
    'mlid' => 0,
    'plid' => 0,
    'menu_name' => 'primary-links',
    'weight' => 0,
    'options' => array(),
    'module' => 'menu',
    'expanded' => 0,
    'hidden' => 0,
    'has_children' => 0,
    'customized' => 0,
    'parent_depth_limit' => 8,
  ),
  'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
  '#_export_node_encode_object' => '1',
);