$content['type']  = array (
  'name' => 'Widget Contest',
  'type' => 'widget_contest',
  'description' => 'A page which describes a widget contest',
  'title_label' => 'Title of the Contest',
  'body_label' => 'Contest Description',
  'min_word_count' => '0',
  'help' => '',
  'node_options' => 
  array (
    'status' => true,
    'promote' => false,
    'sticky' => false,
    'revision' => false,
  ),
  'upload' => '0',
  'old_type' => 'widget_contest',
  'orig_type' => '',
  'module' => 'node',
  'custom' => '1',
  'modified' => '1',
  'locked' => '0',
  'comment' => '0',
  'comment_default_mode' => '4',
  'comment_default_order' => '1',
  'comment_default_per_page' => '50',
  'comment_controls' => '3',
  'comment_anonymous' => '0',
  'comment_subject_field' => '1',
  'comment_preview' => '1',
  'comment_form_location' => '0',
  'fivestar' => 0,
  'fivestar_stars' => 5,
  'fivestar_labels_enable' => 1,
  'fivestar_label_0' => 'Cancel rating',
  'fivestar_label_1' => 'Poor',
  'fivestar_label_2' => 'Okay',
  'fivestar_label_3' => 'Good',
  'fivestar_label_4' => 'Great',
  'fivestar_label_5' => 'Awesome',
  'fivestar_label_6' => 'Give it @star/@count',
  'fivestar_label_7' => 'Give it @star/@count',
  'fivestar_label_8' => 'Give it @star/@count',
  'fivestar_label_9' => 'Give it @star/@count',
  'fivestar_label_10' => 'Give it @star/@count',
  'fivestar_style' => 'average',
  'fivestar_text' => 'dual',
  'fivestar_title' => 1,
  'fivestar_feedback' => 1,
  'fivestar_unvote' => 0,
  'fivestar_position_teaser' => 'hidden',
  'fivestar_position' => 'below',
  'fivestar_comment' => 0,
  'skinr_settings' => 
  array (
    'comment_group' => 
    array (
      'role_widget_store' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
    ),
    'node_group' => 
    array (
      'role_widget_store' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
          'fusion-float-imagefield' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
    ),
  ),
  'better_formats_allowed' => 
  array (
    3 => true,
    1 => false,
    2 => false,
  ),
  'better_formats_defaults' => 
  array (
    'node-1' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-2' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-3' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-5' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-10' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-11' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-12' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-13' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-1' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-2' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-3' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-5' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-10' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-11' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-12' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-13' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
  ),
);
$content['extra']  = array (
  'title' => '-5',
  'body_field' => '0',
  'revision_information' => '20',
  'author' => '20',
  'options' => '25',
  'comment_settings' => '30',
  'menu' => '-2',
  'path' => '30',
  'workflow' => '10',
);
