$content['type']  = array (
  'name' => 'Widget Specification',
  'type' => 'widget_specification',
  'description' => 'This type describes the specification of an widget including screenshot mock-ups, use case and an optional URL to a possible implementation',
  'title_label' => 'Title',
  'body_label' => 'Widget Specification',
  'min_word_count' => '0',
  'help' => 'Use this form to create a widget specification for the ROLE Widget Contest. 

The specification will be saved as draft as long you do not set the status to submitted. Use the "my submissions" link to edit the specification again and see the current status.',
  'node_options' => 
  array (
    'status' => true,
    'promote' => false,
    'sticky' => false,
    'revision' => false,
  ),
  'upload' => '0',
  'old_type' => 'widget_specification',
  'orig_type' => '',
  'module' => 'node',
  'custom' => '1',
  'modified' => '1',
  'locked' => '0',
  'comment' => '0',
  'comment_default_mode' => '4',
  'comment_default_order' => '1',
  'comment_default_per_page' => '50',
  'comment_controls' => '3',
  'comment_anonymous' => '0',
  'comment_subject_field' => '1',
  'comment_preview' => '1',
  'comment_form_location' => '0',
  'fivestar' => 1,
  'fivestar_stars' => '5',
  'fivestar_labels_enable' => 1,
  'fivestar_label_0' => 'Cancel rating',
  'fivestar_label_1' => 'Poor',
  'fivestar_label_2' => 'Okay',
  'fivestar_label_3' => 'Good',
  'fivestar_label_4' => 'Great',
  'fivestar_label_5' => 'Awesome',
  'fivestar_label_6' => 'Give it @star/@count',
  'fivestar_label_7' => 'Give it @star/@count',
  'fivestar_label_8' => 'Give it @star/@count',
  'fivestar_label_9' => 'Give it @star/@count',
  'fivestar_label_10' => 'Give it @star/@count',
  'fivestar_style' => 'average',
  'fivestar_text' => 'dual',
  'fivestar_title' => 0,
  'fivestar_feedback' => 1,
  'fivestar_unvote' => 0,
  'fivestar_position_teaser' => 'hidden',
  'fivestar_position' => 'hidden',
  'fivestar_comment' => '0',
  'skinr_settings' => 
  array (
    'comment_group' => 
    array (
      'role_widget_store' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
      'role_widget_store_embedded' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
    ),
    'node_group' => 
    array (
      'role_widget_store' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
          'fusion-float-imagefield' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
      'role_widget_store_embedded' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
          'fusion-float-imagefield' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
    ),
  ),
  'better_formats_allowed' => 
  array (
    3 => true,
    1 => false,
    2 => false,
  ),
  'better_formats_defaults' => 
  array (
    'node-1' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-2' => 
    array (
      'format' => '3',
      'weight' => '0',
    ),
    'node-3' => 
    array (
      'format' => '3',
      'weight' => '0',
    ),
    'node-4' => 
    array (
      'format' => '3',
      'weight' => '0',
    ),
    'node-5' => 
    array (
      'format' => '3',
      'weight' => '0',
    ),
    'node-6' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'node-7' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-1' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-2' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-3' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-4' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-5' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-6' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
    'comment-7' => 
    array (
      'format' => '0',
      'weight' => '0',
    ),
  ),
);
$content['groups']  = array (
  0 => 
  array (
    'label' => 'Links',
    'group_type' => 'standard',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => '',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
    ),
    'weight' => '2',
    'group_name' => 'group_general',
  ),
  1 => 
  array (
    'label' => 'Images',
    'group_type' => 'standard',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => '',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
    ),
    'weight' => '3',
    'group_name' => 'group_images',
  ),
  2 => 
  array (
    'label' => 'More Details',
    'group_type' => 'standard',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => '',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
    ),
    'weight' => '4',
    'group_name' => 'group_more_details',
  ),
);
$content['fields']  = array (
  0 => 
  array (
    'label' => 'Widget Contest',
    'field_name' => 'field_widget_contest',
    'type' => 'nodereference',
    'widget_type' => 'nodereference_select',
    'change' => 'Change basic information',
    'weight' => '-1',
    'autocomplete_match' => 'contains',
    'size' => 60,
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'nid' => '',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => NULL,
    'group' => false,
    'required' => 1,
    'multiple' => '0',
    'referenceable_types' => 
    array (
      'widget_contest' => 'widget_contest',
      'bundle' => 0,
      'idea' => 0,
      'contest' => 0,
      'review' => 0,
      'lstool_opensocial' => 0,
      'page' => 0,
      'lstool_w3c' => 0,
      'widget_specification' => 0,
      'widget_specification_review' => false,
    ),
    'advanced_view' => '--',
    'advanced_view_args' => '',
    'op' => 'Save field settings',
    'module' => 'nodereference',
    'widget_module' => 'nodereference',
    'columns' => 
    array (
      'nid' => 
      array (
        'type' => 'int',
        'unsigned' => true,
        'not null' => false,
        'index' => true,
      ),
    ),
    'display_settings' => 
    array (
      'label' => 
      array (
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  1 => 
  array (
    'label' => 'Implementation Reference',
    'field_name' => 'field_implementation_reference',
    'type' => 'link',
    'widget_type' => 'link',
    'change' => 'Change basic information',
    'weight' => '15',
    'description' => 'Add here the URL to an implementation of your specification. This is optional and can be an external or internal URL of the Widget Store.',
    'default_value' => 
    array (
      0 => 
      array (
        'url' => '',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_implementation_reference' => 
      array (
        0 => 
        array (
          'url' => '',
        ),
      ),
    ),
    'group' => 'group_general',
    'required' => 0,
    'multiple' => '0',
    'validate_url' => 1,
    'url' => 0,
    'title' => 'none',
    'title_value' => '',
    'enable_tokens' => 0,
    'display' => 
    array (
      'url_cutoff' => '80',
    ),
    'attributes' => 
    array (
      'target' => '_blank',
      'rel' => '',
      'class' => '',
      'title' => '',
    ),
    'op' => 'Save field settings',
    'module' => 'link',
    'widget_module' => 'link',
    'columns' => 
    array (
      'url' => 
      array (
        'type' => 'varchar',
        'length' => 2048,
        'not null' => false,
        'sortable' => true,
      ),
      'title' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'attributes' => 
      array (
        'type' => 'text',
        'size' => 'medium',
        'not null' => false,
      ),
    ),
    'display_settings' => 
    array (
      'label' => 
      array (
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  2 => 
  array (
    'label' => 'Screenshot Mock-ups',
    'field_name' => 'field_screenshot_mockups',
    'type' => 'filefield',
    'widget_type' => 'imagefield_widget',
    'change' => 'Change basic information',
    'weight' => '16',
    'file_extensions' => 'png gif jpg jpeg',
    'progress_indicator' => 'bar',
    'file_path' => '',
    'max_filesize_per_file' => '1MB',
    'max_filesize_per_node' => '10MB',
    'max_resolution' => 0,
    'min_resolution' => 0,
    'custom_alt' => 0,
    'alt' => '',
    'custom_title' => 0,
    'title_type' => 'textfield',
    'title' => '',
    'use_default_image' => 0,
    'default_image_upload' => '',
    'default_image' => NULL,
    'description' => 'Add here screenshot mock-ups of your specification to give the reviewers a better understanding of your specification.',
    'group' => 'group_images',
    'required' => 0,
    'multiple' => '1',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '1',
    'op' => 'Save field settings',
    'module' => 'filefield',
    'widget_module' => 'imagefield',
    'columns' => 
    array (
      'fid' => 
      array (
        'type' => 'int',
        'not null' => false,
        'views' => true,
      ),
      'list' => 
      array (
        'type' => 'int',
        'size' => 'tiny',
        'not null' => false,
        'views' => true,
      ),
      'data' => 
      array (
        'type' => 'text',
        'serialize' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'label' => 
      array (
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
    ),
  ),
  3 => 
  array (
    'label' => 'Use Case',
    'field_name' => 'field_use_case',
    'type' => 'text',
    'widget_type' => 'text_textarea',
    'change' => 'Change basic information',
    'weight' => '17',
    'rows' => '15',
    'size' => 60,
    'description' => 'Provide here a use case of your idea which describes a possible usage of your widget in an educational setting.',
    'default_value' => 
    array (
      0 => 
      array (
        'value' => '',
        '_error_element' => 'default_value_widget][field_use_case][0][value',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_use_case' => 
      array (
        0 => 
        array (
          'value' => '',
          '_error_element' => 'default_value_widget][field_use_case][0][value',
          'format' => 1,
        ),
      ),
    ),
    'group' => 'group_more_details',
    'required' => 0,
    'multiple' => '0',
    'text_processing' => '1',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'op' => 'Save field settings',
    'module' => 'text',
    'widget_module' => 'text',
    'columns' => 
    array (
      'value' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
        'views' => true,
      ),
      'format' => 
      array (
        'type' => 'int',
        'unsigned' => true,
        'not null' => false,
        'views' => false,
      ),
    ),
    'display_settings' => 
    array (
      'label' => 
      array (
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
);
$content['extra']  = array (
  'title' => '-2',
  'body_field' => '0',
  'revision_information' => '8',
  'author' => '7',
  'options' => '9',
  'comment_settings' => '10',
  'menu' => '6',
  'taxonomy' => '1',
  'path' => '11',
  'workflow' => '5',
);
