array(
  //'nid' => '24',
  'type' => 'widget_specification_review',
  'language' => '',
  'uid' => '1',
  'status' => '1',
  'created' => '1331645114',
  'changed' => '1331645143',
  'comment' => '0',
  'promote' => '0',
  'moderate' => '0',
  'sticky' => '0',
  'tnid' => '0',
  'translate' => '0',
  //'vid' => '27',
  'revision_uid' => '1',
  'title' => 'Good Idea',
  'body' => 'The proposed widget can be a valuable addition to the widget store.
However, in its current specification it looks like a replica of the Vocabulary Trainer http://role-widgetstore.eu/tool/vocabulary-trainer
and the Language Resource Browser
http://role-widgetstore.eu/tool/language-resource-browser.

It makes use of ROLE features (W2W communication).

The contribution to the competition objectives are limited, due to its being very similar to existing widgets.',
  'teaser' => 'The proposed widget can be a valuable addition to the widget store.
However, in its current specification it looks like a replica of the Vocabulary Trainer http://role-widgetstore.eu/tool/vocabulary-trainer
and the Language Resource Browser
http://role-widgetstore.eu/tool/language-resource-browser.

It makes use of ROLE features (W2W communication).

The contribution to the competition objectives are limited, due to its being very similar to existing widgets.',
  'log' => '',
  'revision_timestamp' => '1331645143',
  'format' => '1',
  'name' => 'admin',
  'picture' => '',
  'data' => 'a:0:{}',
  'path' => 'specification-review/good-idea',
  'field_creativity_rating' => array(
    '0' => array(
      'rating' => '80',
      'target' => '12',
    ),
  ),
  'field_didactic_value_rating' => array(
    '0' => array(
      'rating' => '40',
      'target' => '12',
    ),
  ),
  'field_impact_rating' => array(
    '0' => array(
      'rating' => '80',
      'target' => '12',
    ),
  ),
  'field_originality_rating' => array(
    '0' => array(
      'rating' => '40',
      'target' => '12',
    ),
  ),
  'field_user_experience_rating' => array(
    '0' => array(
      'rating' => '40',
      'target' => '12',
    ),
  ),
  'field_widget_specification' => array(
    '0' => array(
      'nid' => '12',
    ),
  ),
  '_workflow' => FALSE,
  'last_comment_timestamp' => '1331645114',
  'last_comment_name' => NULL,
  'comment_count' => '0',
  'taxonomy' => array(),
  'imgupload_images' => array(),
  'menu' => array(
    'link_title' => '',
    'mlid' => 0,
    'plid' => 0,
    'menu_name' => 'primary-links',
    'weight' => 0,
    'options' => array(),
    'module' => 'menu',
    'expanded' => 0,
    'hidden' => 0,
    'has_children' => 0,
    'customized' => 0,
    'parent_depth_limit' => 8,
  ),
  '#_export_node_encode_object' => '1',
)