$skinr = array (
  'block' => 
  array (
    'views-Ideas_list_top-block_1' => 
    array (
    ),
    'ideastream_config-0' => 
    array (
    ),
    'views-top_inventors2-block_1' => 
    array (
    ),
    'ideastream_config-1' => 
    array (
    ),
    'ideastream_blocks-0' => 
    array (
    ),
    'ideastream_blocks-1' => 
    array (
    ),
    'menu-menu-my-content' => 
    array (
      'fusion-menu' => 'fusion-inline-menu',
    ),
    'menu-menu-tool-categories' => 
    array (
      '_additional' => 'widget-block-icon',
    ),
    'menu-primary-links' => 
    array (
      'grid12-width' => 'grid12-5',
      'fusion-alignment' => 'fusion-right',
      'fusion-content-alignment' => 'fusion-right-content',
      '_additional' => 'primary-menu',
    ),
    'search-0' => 
    array (
      'grid12-width' => 'grid12-4',
    ),
    'menu-menu-catalogues' => 
    array (
      'grid12-width' => 'grid12-8',
    ),
  ),
  'comment' => 
  array (
    'bundle' => 
    array (
    ),
    'idea' => 
    array (
    ),
    'widget_specification' => 
    array (
    ),
  ),
  'node' => 
  array (
    'bundle' => 
    array (
    ),
    'idea' => 
    array (
    ),
    'widget_specification' => 
    array (
    ),
  ),
  'views' => 
  array (
    'view-widget_specification_review_sum-display-default' => 
    array (
      'grid-width' => 
      array (
      ),
      'fusion-content-alignment' => '',
      'fusion-multicol' => '',
      'fusion-list-styles' => 
      array (
      ),
      'fusion-float-imagefield' => '',
    ),
    'view-widget_spec_review_overview-display-default' => 
    array (
      'grid-width' => 
      array (
      ),
      'fusion-content-alignment' => '',
      'fusion-multicol' => '',
      'fusion-list-styles' => 
      array (
      ),
      'fusion-float-imagefield' => '',
    ),
    'view-my_tools-display-default' => 
    array (
      'grid-width' => 
      array (
      ),
      'fusion-content-alignment' => '',
      'fusion-multicol' => '',
      'fusion-list-styles' => 
      array (
      ),
      'fusion-float-imagefield' => '',
    ),
    'view-my_widget_specification_reviews-display-default' => 
    array (
      'grid-width' => 
      array (
      ),
      'fusion-content-alignment' => '',
      'fusion-multicol' => '',
      'fusion-list-styles' => 
      array (
      ),
      'fusion-float-imagefield' => '',
    ),
    'view-my_widget_specifications-display-default' => 
    array (
      'grid-width' => 
      array (
      ),
      'fusion-content-alignment' => '',
      'fusion-multicol' => '',
      'fusion-list-styles' => 
      array (
      ),
      'fusion-float-imagefield' => '',
    ),
    'view-widget_specification_list-display-default' => 
    array (
      'grid-width' => 
      array (
      ),
      'fusion-content-alignment' => '',
      'fusion-multicol' => '',
      'fusion-list-styles' => 
      array (
      ),
      'fusion-float-imagefield' => '',
    ),
  ),
);