array(
  array(
    'nid' => '25',
    'type' => 'bundle',
    'language' => '',
    'uid' => '1',
    'status' => '0',
    'created' => '1334917196',
    'changed' => '1334921540',
    'comment' => '2',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '25',
    'revision_uid' => '1',
    'title' => 'Sample Bundle',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1334921540',
    'format' => '1',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'bundle/sample-bundle-0',
    'field_bundle_short_description' => array(
      '0' => array(
        'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sollicitudin mollis bibendum. Donec consequat vehicula magna et eleifend. Suspendisse pharetra quam metus. Maecenas elementum ultrices dignissim. Sed sem velit, consequat sed elementum nec, faucibus sit amet arcu. Ut non risus posuere.
',
      ),
    ),
    'field_thumbnail' => array(
      '0' => NULL,
    ),
    'field_use_case' => array(
      '0' => array(
        'value' => NULL,
        'format' => NULL,
      ),
    ),
    'field_bundle_tool' => array(
      '0' => array(
        'nid' => '21',
      ),
    ),
    'field_bundle_tool_activity' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'field_screenshots' => array(
      '0' => NULL,
    ),
    'field_screencasts' => array(
      '0' => array(
        'embed' => NULL,
        'value' => NULL,
        'provider' => NULL,
        'data' => array(
          '0' => FALSE,
        ),
        'status' => '1',
        'version' => '0',
        'title' => NULL,
        'description' => NULL,
        'duration' => '0',
      ),
    ),
    'field_additional_content_title' => array(
      '0' => array(
        'value' => 'ROLE Project Website',
      ),
    ),
    'field_additional_content_file' => array(
      '0' => NULL,
    ),
    'field_additional_content_image' => array(
      '0' => NULL,
    ),
    'field_additional_content_video' => array(
      '0' => array(
        'embed' => NULL,
        'value' => NULL,
        'provider' => NULL,
        'data' => array(
          '0' => FALSE,
        ),
        'status' => '1',
        'version' => '0',
        'title' => NULL,
        'description' => NULL,
        'duration' => '0',
      ),
    ),
    'field_additional_content_link' => array(
      '0' => array(
        'url' => 'http://www.role-project.eu/',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
    'field_additional_content_descrip' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    '_workflow' => FALSE,
    'last_comment_timestamp' => '1334917196',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'imgupload_images' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)