$content['type']  = array (
  'name' => 'Bundle',
  'type' => 'bundle',
  'description' => 'A bundle node type',
  'title_label' => 'Bundle name',
  'body_label' => 'Bundle description',
  'min_word_count' => '0',
  'help' => '',
  'node_options' => 
  array (
    'status' => false,
    'promote' => false,
    'sticky' => false,
    'revision' => false,
  ),
  'upload' => '0',
  'old_type' => 'bundle',
  'orig_type' => '',
  'module' => 'node',
  'custom' => '0',
  'modified' => '1',
  'locked' => '0',
  'reset' => 'Reset to defaults',
  'multistep_expose' => 'enabled',
  'multistep_steps' => '6',
  'multistep_buttons' => 1,
  'multistep_default' => 'multistep',
  'multistep_extra_title' => '1',
  'multistep_extra_body_field' => '2',
  'multistep_extra_revision_information' => '0',
  'multistep_extra_author' => '0',
  'multistep_extra_options' => '0',
  'multistep_extra_comment_settings' => '0',
  'multistep_extra_menu' => '0',
  'multistep_extra_taxonomy_3' => '5',
  'multistep_extra_path' => '0',
  'multistep_extra_workflow' => '0',
  'comment' => '2',
  'comment_default_mode' => '4',
  'comment_default_order' => '1',
  'comment_default_per_page' => '50',
  'comment_controls' => '3',
  'comment_anonymous' => '2',
  'comment_subject_field' => '1',
  'comment_preview' => '0',
  'comment_form_location' => '1',
  'fivestar' => 1,
  'fivestar_stars' => '5',
  'fivestar_labels_enable' => 0,
  'fivestar_label_0' => 'Cancel rating',
  'fivestar_label_1' => 'Poor',
  'fivestar_label_2' => 'Okay',
  'fivestar_label_3' => 'Good',
  'fivestar_label_4' => 'Great',
  'fivestar_label_5' => 'Awesome',
  'fivestar_label_6' => 'Give it @star/@count',
  'fivestar_label_7' => 'Give it @star/@count',
  'fivestar_label_8' => 'Give it @star/@count',
  'fivestar_label_9' => 'Give it @star/@count',
  'fivestar_label_10' => 'Give it @star/@count',
  'fivestar_style' => 'average',
  'fivestar_text' => 'none',
  'fivestar_title' => 0,
  'fivestar_feedback' => 0,
  'fivestar_unvote' => 0,
  'fivestar_position_teaser' => 'below_static',
  'fivestar_position' => 'above_static',
  'fivestar_comment' => '2',
  'skinr_settings' => 
  array (
    'comment_group' => 
    array (
      'role_widget_store' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
      'role_widget_store_embedded' => 
      array (
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
    ),
    'node_group' => 
    array (
      'role_widget_store' => 
      array (
        'widgets' => 
        array (
          'grid-width' => 
          array (
          ),
          'fusion-content-alignment' => '',
          'fusion-float-imagefield' => '',
        ),
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
      'role_widget_store_embedded' => 
      array (
        'advanced' => 
        array (
          '_additional' => '',
          '_template' => '',
        ),
      ),
    ),
  ),
  'better_formats_allowed' => 
  array (
    1 => true,
    2 => false,
    3 => false,
    4 => false,
  ),
  'better_formats_defaults' => 
  array (
    'node-1' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'node-2' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'node-3' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'node-4' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'node-5' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'node-6' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'node-7' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'node-8' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-1' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-2' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-3' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-4' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-5' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-6' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-7' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
    'comment-8' => 
    array (
      'format' => '1',
      'weight' => '25',
    ),
  ),
);
$content['groups']  = array (
  0 => 
  array (
    'label' => 'Basic Information',
    'group_type' => 'standard',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => 'These information are used to provide people an overview about the bundle. It will also be displayed in the list view.',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
      'multistep' => 
      array (
        'step' => '1',
        'block' => 1,
      ),
    ),
    'weight' => '0',
    'group_name' => 'group_basic_information',
    'parent' => '',
  ),
  1 => 
  array (
    'label' => 'Detailed Description',
    'group_type' => 'standard',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => 'The detailed description explains how the bundle should be used. The bundle description is used to explain the general usage of the bundle and the use case describes an example usage of it.',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
      'multistep' => 
      array (
        'step' => '2',
        'block' => 1,
      ),
    ),
    'weight' => '2',
    'group_name' => 'group_detailed_description',
    'parent' => '',
  ),
  2 => 
  array (
    'label' => 'Tools',
    'group_type' => 'multigroup',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => '',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
      'multistep' => 
      array (
        'step' => '3',
        'block' => 1,
      ),
      'multigroup' => 
      array (
        'subgroup' => 
        array (
          'weight' => -20,
          'label' => 'above',
          'teaser' => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          'full' => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          4 => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          2 => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          3 => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          'token' => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
        ),
        'multiple-columns' => 0,
        'required' => 0,
        'multiple' => '1',
        'labels' => 
        array (
          0 => '',
          1 => '',
          2 => '',
          3 => '',
          4 => '',
          5 => '',
          6 => '',
          7 => '',
          8 => '',
          9 => '',
        ),
      ),
    ),
    'weight' => '3',
    'group_name' => 'group_bundle_tools',
    'parent' => '',
  ),
  3 => 
  array (
    'label' => 'Learning Resources',
    'group_type' => 'multigroup',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => '',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
      'multistep' => 
      array (
        'step' => '4',
        'block' => 1,
      ),
      'multigroup' => 
      array (
        'subgroup' => 
        array (
          'weight' => -20,
          'label' => 'above',
          'teaser' => 
          array (
            'format' => 'table-multiple',
            'exclude' => 0,
          ),
          'full' => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          4 => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          2 => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          3 => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
          'token' => 
          array (
            'format' => 'fieldset',
            'exclude' => 0,
          ),
        ),
        'multiple-columns' => 0,
        'required' => 0,
        'multiple' => '1',
        'labels' => 
        array (
          0 => '',
          1 => '',
          2 => '',
          3 => '',
          4 => '',
          5 => '',
          6 => '',
          7 => '',
          8 => '',
          9 => '',
        ),
      ),
    ),
    'weight' => '5',
    'group_name' => 'group_additional_content',
    'parent' => '',
  ),
  4 => 
  array (
    'label' => 'Categorisation',
    'group_type' => 'standard',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => '',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
      'multistep' => 
      array (
        'step' => '5',
        'block' => 1,
      ),
    ),
    'weight' => '9',
    'group_name' => 'group_categorisation',
    'parent' => '',
  ),
  5 => 
  array (
    'label' => 'Media Data',
    'group_type' => 'standard',
    'settings' => 
    array (
      'form' => 
      array (
        'style' => 'fieldset',
        'description' => 'Media data like screenshots and screencasts allow users to see how a bundle looks like and could be used.',
      ),
      'display' => 
      array (
        'description' => '',
        'teaser' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        4 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        2 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        3 => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => 
        array (
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
      'multistep' => 
      array (
        'step' => '6',
        'block' => 1,
      ),
    ),
    'weight' => '12',
    'group_name' => 'group_more_details',
    'parent' => '',
  ),
);
$content['fields']  = array (
  0 => 
  array (
    'label' => 'Bundle Short Description',
    'field_name' => 'field_bundle_short_description',
    'type' => 'text',
    'widget_type' => 'text_textarea',
    'change' => 'Change basic information',
    'weight' => '1',
    'rows' => '5',
    'size' => 60,
    'description' => 'This short description should give other users an overview of the bundle. It will be displayed on overview pages and at the top of the detail page.',
    'default_value' => 
    array (
      0 => 
      array (
        'value' => '',
        '_error_element' => 'default_value_widget][field_bundle_short_description][0][value',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => NULL,
    'group' => 'group_basic_information',
    'required' => 1,
    'multiple' => '0',
    'text_processing' => '0',
    'max_length' => '1000',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'op' => 'Save field settings',
    'module' => 'text',
    'widget_module' => 'text',
    'columns' => 
    array (
      'value' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '1',
      'parent' => 'group_basic_information',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  1 => 
  array (
    'label' => 'Thumbnail',
    'field_name' => 'field_thumbnail',
    'type' => 'filefield',
    'widget_type' => 'imagefield_widget',
    'change' => 'Change basic information',
    'weight' => '2',
    'file_extensions' => 'png gif jpg jpeg',
    'progress_indicator' => 'bar',
    'file_path' => 'images/thumbnails',
    'max_filesize_per_file' => '',
    'max_filesize_per_node' => '',
    'max_resolution' => '110x110',
    'min_resolution' => 0,
    'custom_alt' => 0,
    'alt' => 'Bundle Thumbnail',
    'custom_title' => 0,
    'title_type' => 'textfield',
    'title' => '',
    'use_default_image' => 1,
    'default_image_upload' => '',
    'default_image' => 
    array (
      'filename' => 'default_bundle_thumbnail.png',
      'filepath' => 'sites/default/files/imagefield_default_images/default_bundle_thumbnail_0.png',
      'filemime' => 'image/png',
      'source' => 'default_image_upload',
      'destination' => 'sites/default/files/imagefield_default_images/default_bundle_thumbnail_0.png',
      'filesize' => 6169,
      'uid' => '1',
      'status' => 1,
      'timestamp' => 1331817802,
      'fid' => '22',
    ),
    'description' => 'This image will appear at overview pages and at the top of the detail page.',
    'group' => 'group_basic_information',
    'required' => 0,
    'multiple' => '0',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '0',
    'op' => 'Save field settings',
    'module' => 'filefield',
    'widget_module' => 'imagefield',
    'columns' => 
    array (
      'fid' => 
      array (
        'type' => 'int',
        'not null' => false,
        'views' => true,
      ),
      'list' => 
      array (
        'type' => 'int',
        'size' => 'tiny',
        'not null' => false,
        'views' => true,
      ),
      'data' => 
      array (
        'type' => 'text',
        'serialize' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '2',
      'parent' => 'group_basic_information',
      'label' => 
      array (
        'format' => 'hidden',
      ),
      'teaser' => 
      array (
        'format' => 'image_nodelink',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
    ),
  ),
  2 => 
  array (
    'label' => 'Use Case',
    'field_name' => 'field_use_case',
    'type' => 'text',
    'widget_type' => 'text_textarea',
    'change' => 'Change basic information',
    'weight' => '5',
    'rows' => '15',
    'size' => 60,
    'description' => 'Provide here a use case of your idea which describes a possible usage of your widget in an educational setting.',
    'default_value' => 
    array (
      0 => 
      array (
        'value' => '',
        'format' => '1',
        '_error_element' => 'default_value_widget][field_use_case][0][value',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_use_case' => 
      array (
        0 => 
        array (
          'value' => '',
          'format' => '1',
          '_error_element' => 'default_value_widget][field_use_case][0][value',
        ),
      ),
    ),
    'group' => 'group_detailed_description',
    'required' => 0,
    'multiple' => '0',
    'text_processing' => '1',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'op' => 'Save field settings',
    'module' => 'text',
    'widget_module' => 'text',
    'columns' => 
    array (
      'value' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
        'views' => true,
      ),
      'format' => 
      array (
        'type' => 'int',
        'unsigned' => true,
        'not null' => false,
        'views' => false,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '5',
      'parent' => 'group_detailed_description',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  3 => 
  array (
    'label' => 'Tool',
    'field_name' => 'field_bundle_tool',
    'type' => 'nodereference',
    'widget_type' => 'nodereference_explorer',
    'change' => 'Change basic information',
    'weight' => '7',
    'autocomplete_match' => 'contains',
    'size' => '60',
    'create_ref' => 0,
    'content_preview' => 'preview',
    'content_preview_position' => 'below',
    'dialog_title' => 'Tool Explorer',
    'dialog_width@int' => '800',
    'dialog_height@int' => '600',
    'dialog_api' => 'modalframe',
    'dialog_position' => 'center',
    'theme_css' => '<module>',
    'dialog_dialogClass' => '',
    'dialog_bgiframe@boolean' => '0',
    'dialog_minWidth@int' => '',
    'dialog_minHeight@int' => '',
    'dialog_maxWidth@int' => '',
    'dialog_maxHeight@int' => '',
    'dialog_draggable@boolean' => '0',
    'dialog_resizable@boolean' => '0',
    'dialog_closeOnEscape@boolean' => 0,
    'dialog_show' => 'null',
    'dialog_hide' => 'null',
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'nid' => NULL,
        '_error_element' => 'default_value_widget][field_bundle_tool][0][nid][nid',
        'actions' => 
        array (
          'browse' => 'Browse',
          'remove' => 'Remove',
        ),
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_bundle_tool' => 
      array (
        0 => 
        array (
          'nid' => 
          array (
            'nid' => '',
            '_error_element' => 'default_value_widget][field_bundle_tool][0][nid][nid',
          ),
          '_error_element' => 'default_value_widget][field_bundle_tool][0][nid][nid',
          'actions' => 
          array (
            'browse' => 'Browse',
            'remove' => 'Remove',
          ),
        ),
      ),
    ),
    'group' => 'group_bundle_tools',
    'required' => 0,
    'multiple' => '1',
    'referenceable_types' => 
    array (
      'lstool_opensocial' => 'lstool_opensocial',
      'lstool_w3c' => 'lstool_w3c',
      'bundle' => 0,
      'bundle_tool_reference' => 0,
      'faq' => 0,
      'page' => 0,
      'user_report' => 0,
      'widget_contest' => 0,
      'widget_specification' => 0,
      'widget_specification_review' => 0,
    ),
    'advanced_view' => 'bundle_tool_browser',
    'advanced_view_args' => '',
    'op' => 'Save field settings',
    'module' => 'nodereference',
    'widget_module' => 'nodereference_explorer',
    'columns' => 
    array (
      'nid' => 
      array (
        'type' => 'int',
        'unsigned' => true,
        'not null' => false,
        'index' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '7',
      'parent' => 'group_bundle_tools',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  4 => 
  array (
    'label' => 'Description',
    'field_name' => 'field_bundle_tool_activity',
    'type' => 'text',
    'widget_type' => 'text_textarea',
    'change' => 'Change basic information',
    'weight' => '8',
    'rows' => '5',
    'size' => 60,
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'value' => '',
        '_error_element' => 'default_value_widget][field_bundle_tool_activity][0][value',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_bundle_tool_activity' => 
      array (
        0 => 
        array (
          'value' => '',
          '_error_element' => 'default_value_widget][field_bundle_tool_activity][0][value',
        ),
      ),
    ),
    'group' => 'group_bundle_tools',
    'required' => 0,
    'multiple' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'op' => 'Save field settings',
    'module' => 'text',
    'widget_module' => 'text',
    'columns' => 
    array (
      'value' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '8',
      'parent' => 'group_bundle_tools',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  5 => 
  array (
    'label' => 'Title',
    'field_name' => 'field_additional_content_title',
    'type' => 'text',
    'widget_type' => 'text_textfield',
    'change' => 'Change basic information',
    'weight' => '20',
    'rows' => 5,
    'size' => '60',
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'value' => '',
        '_error_element' => 'default_value_widget][field_additional_content_title][0][value',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_additional_content_title' => 
      array (
        0 => 
        array (
          'value' => '',
          '_error_element' => 'default_value_widget][field_additional_content_title][0][value',
        ),
      ),
    ),
    'group' => 'group_additional_content',
    'required' => 0,
    'multiple' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'op' => 'Save field settings',
    'module' => 'text',
    'widget_module' => 'text',
    'columns' => 
    array (
      'value' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '20',
      'parent' => 'group_additional_content',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  6 => 
  array (
    'label' => 'File',
    'field_name' => 'field_additional_content_file',
    'type' => 'filefield',
    'widget_type' => 'filefield_widget',
    'change' => 'Change basic information',
    'weight' => '21',
    'file_extensions' => '',
    'progress_indicator' => 'bar',
    'file_path' => '',
    'max_filesize_per_file' => '',
    'max_filesize_per_node' => '',
    'description' => '',
    'group' => 'group_additional_content',
    'required' => 0,
    'multiple' => '1',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '0',
    'op' => 'Save field settings',
    'module' => 'filefield',
    'widget_module' => 'filefield',
    'columns' => 
    array (
      'fid' => 
      array (
        'type' => 'int',
        'not null' => false,
        'views' => true,
      ),
      'list' => 
      array (
        'type' => 'int',
        'size' => 'tiny',
        'not null' => false,
        'views' => true,
      ),
      'data' => 
      array (
        'type' => 'text',
        'serialize' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '21',
      'parent' => 'group_additional_content',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  7 => 
  array (
    'label' => 'Image',
    'field_name' => 'field_additional_content_image',
    'type' => 'filefield',
    'widget_type' => 'imagefield_widget',
    'change' => 'Change basic information',
    'weight' => '22',
    'file_extensions' => 'png gif jpg jpeg',
    'progress_indicator' => 'bar',
    'file_path' => '',
    'max_filesize_per_file' => '',
    'max_filesize_per_node' => '',
    'max_resolution' => 0,
    'min_resolution' => 0,
    'custom_alt' => 0,
    'alt' => '',
    'custom_title' => 0,
    'title_type' => 'textfield',
    'title' => '',
    'use_default_image' => 0,
    'default_image_upload' => '',
    'default_image' => NULL,
    'description' => '',
    'group' => 'group_additional_content',
    'required' => 0,
    'multiple' => '1',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '0',
    'op' => 'Save field settings',
    'module' => 'filefield',
    'widget_module' => 'imagefield',
    'columns' => 
    array (
      'fid' => 
      array (
        'type' => 'int',
        'not null' => false,
        'views' => true,
      ),
      'list' => 
      array (
        'type' => 'int',
        'size' => 'tiny',
        'not null' => false,
        'views' => true,
      ),
      'data' => 
      array (
        'type' => 'text',
        'serialize' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '22',
      'parent' => 'group_additional_content',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'bundle_list_50x50_linked',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'imagefield__lightbox2__wysiwyg_200x200__original',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
    ),
  ),
  8 => 
  array (
    'label' => 'Video',
    'field_name' => 'field_additional_content_video',
    'type' => 'emvideo',
    'widget_type' => 'emvideo_textfields',
    'change' => 'Change basic information',
    'weight' => '23',
    'providers' => 
    array (
      1 => 1,
      'hulu' => false,
      'vimeo' => false,
      'youtube' => false,
    ),
    'video_width' => '425',
    'video_height' => '350',
    'video_autoplay' => '',
    'preview_width' => '300',
    'preview_height' => '200',
    'preview_autoplay' => '',
    'thumbnail_width' => '120',
    'thumbnail_height' => '90',
    'thumbnail_default_path' => '',
    'thumbnail_link_title' => 'See video',
    'meta_fields' => 
    array (
      1 => 1,
      0 => 1,
      'title' => false,
      'description' => false,
    ),
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'embed' => '',
        'value' => '',
        'emvideo' => 
        array (
          'title' => '',
        ),
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_additional_content_video' => 
      array (
        0 => 
        array (
          'embed' => '',
          'value' => '',
        ),
      ),
    ),
    'group' => 'group_additional_content',
    'required' => 0,
    'multiple' => '1',
    'op' => 'Save field settings',
    'module' => 'emvideo',
    'widget_module' => 'emvideo',
    'columns' => 
    array (
      'embed' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
      ),
      'value' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'provider' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'data' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => false,
      ),
      'status' => 
      array (
        'description' => 'The availability status of this media.',
        'type' => 'int',
        'unsigned' => 'TRUE',
        'not null' => true,
        'default' => 1,
      ),
      'version' => 
      array (
        'description' => 'The version of the provider\'s data.',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
        'default' => 0,
      ),
      'title' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'description' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'duration' => 
      array (
        'description' => 'Store the duration of a video in seconds.',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
        'default' => 0,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '23',
      'parent' => 'group_additional_content',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'video_preview',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'lightbox2',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  9 => 
  array (
    'label' => 'Link',
    'field_name' => 'field_additional_content_link',
    'type' => 'link',
    'widget_type' => 'link',
    'change' => 'Change basic information',
    'weight' => '24',
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'title' => '',
        'url' => '',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_additional_content_link' => 
      array (
        0 => 
        array (
          'title' => '',
          'url' => '',
        ),
      ),
    ),
    'group' => 'group_additional_content',
    'required' => 0,
    'multiple' => '1',
    'validate_url' => 1,
    'url' => 0,
    'title' => 'none',
    'title_value' => '',
    'enable_tokens' => 0,
    'display' => 
    array (
      'url_cutoff' => '80',
    ),
    'attributes' => 
    array (
      'target' => '_blank',
      'rel' => '',
      'class' => '',
      'title' => '',
    ),
    'op' => 'Save field settings',
    'module' => 'link',
    'widget_module' => 'link',
    'columns' => 
    array (
      'url' => 
      array (
        'type' => 'varchar',
        'length' => 2048,
        'not null' => false,
        'sortable' => true,
      ),
      'title' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'attributes' => 
      array (
        'type' => 'text',
        'size' => 'medium',
        'not null' => false,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '24',
      'parent' => 'group_additional_content',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'url',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'url',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  10 => 
  array (
    'label' => 'Description',
    'field_name' => 'field_additional_content_descrip',
    'type' => 'text',
    'widget_type' => 'text_textarea',
    'change' => 'Change basic information',
    'weight' => '25',
    'rows' => '5',
    'size' => 60,
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'value' => '',
        '_error_element' => 'default_value_widget][field_additional_content_descrip][0][value',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_additional_content_descrip' => 
      array (
        0 => 
        array (
          'value' => '',
          '_error_element' => 'default_value_widget][field_additional_content_descrip][0][value',
        ),
      ),
    ),
    'group' => 'group_additional_content',
    'required' => 0,
    'multiple' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'op' => 'Save field settings',
    'module' => 'text',
    'widget_module' => 'text',
    'columns' => 
    array (
      'value' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '25',
      'parent' => 'group_additional_content',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
  11 => 
  array (
    'label' => 'Screenshots',
    'field_name' => 'field_screenshots',
    'type' => 'filefield',
    'widget_type' => 'imagefield_widget',
    'change' => 'Change basic information',
    'weight' => '11',
    'file_extensions' => 'png gif jpg jpeg',
    'progress_indicator' => 'bar',
    'file_path' => 'images/screenshots',
    'max_filesize_per_file' => '1MB',
    'max_filesize_per_node' => '10MB',
    'max_resolution' => 0,
    'min_resolution' => 0,
    'custom_alt' => 0,
    'alt' => '',
    'custom_title' => 0,
    'title_type' => 'textfield',
    'title' => '',
    'use_default_image' => 0,
    'default_image_upload' => '',
    'default_image' => 
    array (
      'filename' => 'screenshot-none.png',
      'filepath' => 'sites/default/files/imagefield_default_images/screenshot-none.png',
      'filemime' => 'image/png',
      'source' => 'default_image_upload',
      'destination' => 'sites/default/files/imagefield_default_images/screenshot-none.png',
      'filesize' => 3883,
      'uid' => '1',
      'status' => 1,
      'timestamp' => 1320668972,
      'fid' => '2',
    ),
    'description' => 'These images will be shown in a special tab on the detail page.',
    'group' => 'group_more_details',
    'required' => 0,
    'multiple' => '1',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '1',
    'op' => 'Save field settings',
    'module' => 'filefield',
    'widget_module' => 'imagefield',
    'columns' => 
    array (
      'fid' => 
      array (
        'type' => 'int',
        'not null' => false,
        'views' => true,
      ),
      'list' => 
      array (
        'type' => 'int',
        'size' => 'tiny',
        'not null' => false,
        'views' => true,
      ),
      'data' => 
      array (
        'type' => 'text',
        'serialize' => true,
        'views' => true,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '11',
      'parent' => 'group_more_details',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'image_plain',
        'exclude' => 0,
      ),
    ),
  ),
  12 => 
  array (
    'label' => 'Screencasts',
    'field_name' => 'field_screencasts',
    'type' => 'emvideo',
    'widget_type' => 'emvideo_textfields',
    'change' => 'Change basic information',
    'weight' => '12',
    'providers' => 
    array (
      1 => 1,
      0 => 1,
      'hulu' => false,
      'vimeo' => false,
      'youtube' => false,
    ),
    'video_width' => '420',
    'video_height' => '315',
    'video_autoplay' => '',
    'preview_width' => '425',
    'preview_height' => '350',
    'preview_autoplay' => '',
    'thumbnail_width' => '120',
    'thumbnail_height' => '90',
    'thumbnail_default_path' => '',
    'thumbnail_link_title' => 'See video',
    'meta_fields' => 
    array (
      1 => 1,
      0 => 1,
      'title' => false,
      'description' => false,
    ),
    'description' => '',
    'default_value' => 
    array (
      0 => 
      array (
        'embed' => '',
        'value' => '',
      ),
    ),
    'default_value_php' => '',
    'default_value_widget' => 
    array (
      'field_screencasts' => 
      array (
        0 => 
        array (
          'embed' => '',
          'value' => '',
        ),
      ),
    ),
    'group' => 'group_more_details',
    'required' => 0,
    'multiple' => '1',
    'op' => 'Save field settings',
    'module' => 'emvideo',
    'widget_module' => 'emvideo',
    'columns' => 
    array (
      'embed' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => true,
      ),
      'value' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'provider' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'data' => 
      array (
        'type' => 'text',
        'size' => 'big',
        'not null' => false,
        'sortable' => false,
      ),
      'status' => 
      array (
        'description' => 'The availability status of this media.',
        'type' => 'int',
        'unsigned' => 'TRUE',
        'not null' => true,
        'default' => 1,
      ),
      'version' => 
      array (
        'description' => 'The version of the provider\'s data.',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
        'default' => 0,
      ),
      'title' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'description' => 
      array (
        'type' => 'varchar',
        'length' => 255,
        'not null' => false,
        'sortable' => true,
      ),
      'duration' => 
      array (
        'description' => 'Store the duration of a video in seconds.',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
        'default' => 0,
      ),
    ),
    'display_settings' => 
    array (
      'weight' => '12',
      'parent' => 'group_more_details',
      'label' => 
      array (
        'format' => 'above',
      ),
      'teaser' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      4 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      2 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      3 => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => 
      array (
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
  ),
);
$content['extra']  = array (
  'title' => '-1',
  'body_field' => '1',
  'revision_information' => '8',
  'author' => '7',
  'options' => '9',
  'comment_settings' => '12',
  'menu' => '-2',
  'taxonomy' => '5',
  'path' => '11',
  'workflow' => '6',
);
